/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RecurringScheduleTemplateDto } from './recurringScheduleTemplateDto';
import { FitnessClassesDto } from './fitnessClassesDto';


export interface AdminClassScheduleResponseDto { 
    id?: string;
    fitnessClassDto?: FitnessClassesDto;
    instructorName?: string;
    status?: AdminClassScheduleResponseDto.StatusEnum;
    startTime?: string;
    endTime?: string;
    templateDto?: RecurringScheduleTemplateDto;
    capacity?: number;
    bookedCount?: number;
}
export namespace AdminClassScheduleResponseDto {
    export const StatusEnum = {
        Scheduled: 'SCHEDULED',
        Cancelled: 'CANCELLED'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


