/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AuthResponseDto { 
    accessToken?: string;
    name?: string;
    email?: string;
    role?: AuthResponseDto.RoleEnum;
}
export namespace AuthResponseDto {
    export const RoleEnum = {
        Admin: 'ADMIN',
        Instructor: 'INSTRUCTOR',
        Client: 'CLIENT'
    } as const;
    export type RoleEnum = typeof RoleEnum[keyof typeof RoleEnum];
}


