/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BookingResponseDto { 
    id?: string;
    userId?: string;
    userName?: string;
    classScheduleId?: string;
    fitnessClassName?: string;
    instructorName?: string;
    startTime?: string;
    endTime?: string;
    status?: BookingResponseDto.StatusEnum;
}
export namespace BookingResponseDto {
    export const StatusEnum = {
        Pending: 'PENDING',
        Confirmed: 'CONFIRMED',
        Cancelled: 'CANCELLED'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


