/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RecurringScheduleTemplateDto } from './recurringScheduleTemplateDto';
import { FitnessClassesDto } from './fitnessClassesDto';
import { InstructorDto } from './instructorDto';


export interface ClassScheduleResponseDto { 
    id?: string;
    fitnessClassDto?: FitnessClassesDto;
    instructorDto?: InstructorDto;
    startTime?: string;
    endTime?: string;
    templateDto?: RecurringScheduleTemplateDto;
}

