/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserStatusUpdateRequest { 
    userStatus: UserStatusUpdateRequest.UserStatusEnum;
}
export namespace UserStatusUpdateRequest {
    export const UserStatusEnum = {
        Pending: 'PENDING',
        Active: 'ACTIVE',
        Rejected: 'REJECTED',
        Blocked: 'BLOCKED'
    } as const;
    export type UserStatusEnum = typeof UserStatusEnum[keyof typeof UserStatusEnum];
}


