/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BookingResponseDto {
  classScheduleId?: string;
  endTime?: string;
  fitnessClassName?: string;
  id?: string;
  instructorName?: string;
  startTime?: string;
  status?: 'PENDING' | 'CONFIRMED' | 'CANCELLED';
  userId?: string;
  userName?: string;
}
