/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FitnessClassesDto } from '../models/fitness-classes-dto';
import { InstructorDto } from '../models/instructor-dto';
import { RecurringScheduleTemplateDto } from '../models/recurring-schedule-template-dto';
export interface ClassScheduleResponseDto {
  endTime?: string;
  fitnessClassDto?: FitnessClassesDto;
  id?: string;
  instructorDto?: InstructorDto;
  startTime?: string;
  templateDto?: RecurringScheduleTemplateDto;
}
