/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface FitnessClassesResponseDto {
  capacity?: number;
  category?: string;
  description?: string;
  durationMinutes?: number;
  id?: string;
  name?: string;
}
