/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface FitnessClassesDto {
  capacity?: number;
  category?: string;
  description?: string;
  durationMinutes?: number;
  name?: string;
}
