/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RoleDto } from '../models/role-dto';
export interface UserRegistrationRequestDto {
  email?: string;
  name?: string;
  password?: string;
  roleDto?: RoleDto;
}
