/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FitnessClassesDto } from '../../models/fitness-classes-dto';
import { FitnessClassesResponseDto } from '../../models/fitness-classes-response-dto';

export interface CreateFitnessClass$Params {
      body: FitnessClassesDto
}

export function createFitnessClass(http: HttpClient, rootUrl: string, params: CreateFitnessClass$Params, context?: HttpContext): Observable<StrictHttpResponse<FitnessClassesResponseDto>> {
  const rb = new RequestBuilder(rootUrl, createFitnessClass.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<FitnessClassesResponseDto>;
    })
  );
}

createFitnessClass.PATH = '/api/v1/fitnessClasses';
