/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FitnessClassesDto } from '../../models/fitness-classes-dto';

export interface UpdateFitnessClass$Params {
  id: string;
      body: FitnessClassesDto
}

export function updateFitnessClass(http: HttpClient, rootUrl: string, params: UpdateFitnessClass$Params, context?: HttpContext): Observable<StrictHttpResponse<FitnessClassesDto>> {
  const rb = new RequestBuilder(rootUrl, updateFitnessClass.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<FitnessClassesDto>;
    })
  );
}

updateFitnessClass.PATH = '/api/v1/fitnessClasses/{id}';
