/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { GetFitnessClassById$Params as GetFitnessClassById$Params } from './fn/fitness-classes-controller/get-fitness-class-by-id';
export { getFitnessClassById as getFitnessClassById } from './fn/fitness-classes-controller/get-fitness-class-by-id';
export type { UpdateFitnessClass$Params as UpdateFitnessClass$Params } from './fn/fitness-classes-controller/update-fitness-class';
export { updateFitnessClass as updateFitnessClass } from './fn/fitness-classes-controller/update-fitness-class';
export type { GetAllFitnessClasses$Params as GetAllFitnessClasses$Params } from './fn/fitness-classes-controller/get-all-fitness-classes';
export { getAllFitnessClasses as getAllFitnessClasses } from './fn/fitness-classes-controller/get-all-fitness-classes';
export type { CreateFitnessClass$Params as CreateFitnessClass$Params } from './fn/fitness-classes-controller/create-fitness-class';
export { createFitnessClass as createFitnessClass } from './fn/fitness-classes-controller/create-fitness-class';
export type { GetAllClassSchedules$Params as GetAllClassSchedules$Params } from './fn/class-schedules-controller/get-all-class-schedules';
export { getAllClassSchedules as getAllClassSchedules } from './fn/class-schedules-controller/get-all-class-schedules';
export type { CreateClassSchedules$Params as CreateClassSchedules$Params } from './fn/class-schedules-controller/create-class-schedules';
export { createClassSchedules as createClassSchedules } from './fn/class-schedules-controller/create-class-schedules';
export type { GetClassScheduleById$Params as GetClassScheduleById$Params } from './fn/class-schedules-controller/get-class-schedule-by-id';
export { getClassScheduleById as getClassScheduleById } from './fn/class-schedules-controller/get-class-schedule-by-id';
export type { GetAllBookings$Params as GetAllBookings$Params } from './fn/booking-controller/get-all-bookings';
export { getAllBookings as getAllBookings } from './fn/booking-controller/get-all-bookings';
export type { CreateBooking$Params as CreateBooking$Params } from './fn/booking-controller/create-booking';
export { createBooking as createBooking } from './fn/booking-controller/create-booking';
export type { UpdateBookingStatus$Params as UpdateBookingStatus$Params } from './fn/booking-controller/update-booking-status';
export { updateBookingStatus as updateBookingStatus } from './fn/booking-controller/update-booking-status';
export type { GetBookingById$Params as GetBookingById$Params } from './fn/booking-controller/get-booking-by-id';
export { getBookingById as getBookingById } from './fn/booking-controller/get-booking-by-id';
export type { GetMyBookings$Params as GetMyBookings$Params } from './fn/booking-controller/get-my-bookings';
export { getMyBookings as getMyBookings } from './fn/booking-controller/get-my-bookings';
export type { Register$Params as Register$Params } from './fn/authentication-controller/register';
export { register as register } from './fn/authentication-controller/register';
export type { ApplyAsInstructor$Params as ApplyAsInstructor$Params } from './fn/authentication-controller/apply-as-instructor';
export { applyAsInstructor as applyAsInstructor } from './fn/authentication-controller/apply-as-instructor';
export type { Login$Params as Login$Params } from './fn/authentication-controller/login';
export { login as login } from './fn/authentication-controller/login';
export type { UpdateInstructorStatus$Params as UpdateInstructorStatus$Params } from './fn/admin-controller/update-instructor-status';
export { updateInstructorStatus as updateInstructorStatus } from './fn/admin-controller/update-instructor-status';
export type { GetPendingInstructor$Params as GetPendingInstructor$Params } from './fn/admin-controller/get-pending-instructor';
export { getPendingInstructor as getPendingInstructor } from './fn/admin-controller/get-pending-instructor';
