/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { ApplicationResponseDto } from './models/application-response-dto';
export type { AuthRequestDto } from './models/auth-request-dto';
export type { AuthResponseDto } from './models/auth-response-dto';
export type { BookingRequestDto } from './models/booking-request-dto';
export type { BookingResponseDto } from './models/booking-response-dto';
export type { ClassScheduleRequestDto } from './models/class-schedule-request-dto';
export type { ClassScheduleResponseDto } from './models/class-schedule-response-dto';
export type { FitnessClassesDto } from './models/fitness-classes-dto';
export type { FitnessClassesResponseDto } from './models/fitness-classes-response-dto';
export type { InstructorApplicationRequest } from './models/instructor-application-request';
export type { InstructorDto } from './models/instructor-dto';
export type { InstructorResponseDto } from './models/instructor-response-dto';
export type { Pageable } from './models/pageable';
export type { RecurringScheduleTemplateDto } from './models/recurring-schedule-template-dto';
export type { RoleDto } from './models/role-dto';
export type { StatusUpdateRequest } from './models/status-update-request';
export type { UserRegistrationRequestDto } from './models/user-registration-request-dto';
export type { UserStatusUpdateRequest } from './models/user-status-update-request';
