/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ClassScheduleResponseDto } from '../../models/class-schedule-response-dto';

export interface GetAllClassSchedules$Params {
}

export function getAllClassSchedules(http: HttpClient, rootUrl: string, params?: GetAllClassSchedules$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ClassScheduleResponseDto>>> {
  const rb = new RequestBuilder(rootUrl, getAllClassSchedules.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ClassScheduleResponseDto>>;
    })
  );
}

getAllClassSchedules.PATH = '/api/v1/class-schedules';
