/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ClassScheduleResponseDto } from '../../models/class-schedule-response-dto';

export interface GetClassScheduleById$Params {
  id: string;
}

export function getClassScheduleById(http: HttpClient, rootUrl: string, params: GetClassScheduleById$Params, context?: HttpContext): Observable<StrictHttpResponse<ClassScheduleResponseDto>> {
  const rb = new RequestBuilder(rootUrl, getClassScheduleById.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ClassScheduleResponseDto>;
    })
  );
}

getClassScheduleById.PATH = '/api/v1/class-schedules/{id}';
