/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BookingRequestDto } from '../../models/booking-request-dto';
import { BookingResponseDto } from '../../models/booking-response-dto';

export interface CreateBooking$Params {
      body: BookingRequestDto
}

export function createBooking(http: HttpClient, rootUrl: string, params: CreateBooking$Params, context?: HttpContext): Observable<StrictHttpResponse<BookingResponseDto>> {
  const rb = new RequestBuilder(rootUrl, createBooking.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BookingResponseDto>;
    })
  );
}

createBooking.PATH = '/api/v1/bookings/';
