/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BookingResponseDto } from '../../models/booking-response-dto';
import { Pageable } from '../../models/pageable';

export interface GetMyBookings$Params {
  pageable: Pageable;
}

export function getMyBookings(http: HttpClient, rootUrl: string, params: GetMyBookings$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<BookingResponseDto>>> {
  const rb = new RequestBuilder(rootUrl, getMyBookings.PATH, 'get');
  if (params) {
    rb.query('pageable', params.pageable, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<BookingResponseDto>>;
    })
  );
}

getMyBookings.PATH = '/api/v1/bookings/my-bookings';
