/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BookingResponseDto } from '../../models/booking-response-dto';
import { StatusUpdateRequest } from '../../models/status-update-request';

export interface UpdateBookingStatus$Params {
  id: string;
      body: StatusUpdateRequest
}

export function updateBookingStatus(http: HttpClient, rootUrl: string, params: UpdateBookingStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<BookingResponseDto>> {
  const rb = new RequestBuilder(rootUrl, updateBookingStatus.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BookingResponseDto>;
    })
  );
}

updateBookingStatus.PATH = '/api/v1/bookings/{id}/status';
