/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApplicationResponseDto } from '../../models/application-response-dto';
import { InstructorApplicationRequest } from '../../models/instructor-application-request';

export interface ApplyAsInstructor$Params {
      body: InstructorApplicationRequest
}

export function applyAsInstructor(http: HttpClient, rootUrl: string, params: ApplyAsInstructor$Params, context?: HttpContext): Observable<StrictHttpResponse<ApplicationResponseDto>> {
  const rb = new RequestBuilder(rootUrl, applyAsInstructor.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApplicationResponseDto>;
    })
  );
}

applyAsInstructor.PATH = '/api/v1/auth/register-instructor';
