export * from './adminClientController.service';
import { AdminClientControllerService } from './adminClientController.service';
export * from './adminDashboardController.service';
import { AdminDashboardControllerService } from './adminDashboardController.service';
export * from './adminInstructorController.service';
import { AdminInstructorControllerService } from './adminInstructorController.service';
export * from './adminScheduleController.service';
import { AdminScheduleControllerService } from './adminScheduleController.service';
export * from './authenticationController.service';
import { AuthenticationControllerService } from './authenticationController.service';
export * from './bookingController.service';
import { BookingControllerService } from './bookingController.service';
export * from './categoryController.service';
import { CategoryControllerService } from './categoryController.service';
export * from './classSchedulesController.service';
import { ClassSchedulesControllerService } from './classSchedulesController.service';
export * from './fitnessClassesController.service';
import { FitnessClassesControllerService } from './fitnessClassesController.service';
export const APIS = [AdminClientControllerService, AdminDashboardControllerService, AdminInstructorControllerService, AdminScheduleControllerService, AuthenticationControllerService, BookingControllerService, CategoryControllerService, ClassSchedulesControllerService, FitnessClassesControllerService];
