export * from './adminClientController.service';
import { AdminClientControllerService } from './adminClientController.service';
export * from './adminInstructorController.service';
import { AdminInstructorControllerService } from './adminInstructorController.service';
export * from './authenticationController.service';
import { AuthenticationControllerService } from './authenticationController.service';
export * from './bookingController.service';
import { BookingControllerService } from './bookingController.service';
export * from './classSchedulesController.service';
import { ClassSchedulesControllerService } from './classSchedulesController.service';
export * from './fitnessClassesController.service';
import { FitnessClassesControllerService } from './fitnessClassesController.service';
export const APIS = [AdminClientControllerService, AdminInstructorControllerService, AuthenticationControllerService, BookingControllerService, ClassSchedulesControllerService, FitnessClassesControllerService];
