/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RecurringScheduleTemplateDto } from './recurringScheduleTemplateDto';


export interface ClassScheduleRequestDto { 
    fitnessClassId?: string;
    startTime?: string;
    endTime?: string;
    templateDto?: RecurringScheduleTemplateDto;
}

