/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface InstructorResponseDto { 
    instructorId?: string;
    name?: string;
    email?: string;
    bio?: string;
    specialization?: string;
}

