/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RoleDto { 
    name?: RoleDto.NameEnum;
}
export namespace RoleDto {
    export const NameEnum = {
        Admin: 'ADMIN',
        Instructor: 'INSTRUCTOR',
        Client: 'CLIENT'
    } as const;
    export type NameEnum = typeof NameEnum[keyof typeof NameEnum];
}


