/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { InstructorResponseDto } from '../../models/instructor-response-dto';

export interface GetPendingInstructor$Params {
}

export function getPendingInstructor(http: HttpClient, rootUrl: string, params?: GetPendingInstructor$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<InstructorResponseDto>>> {
  const rb = new RequestBuilder(rootUrl, getPendingInstructor.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<InstructorResponseDto>>;
    })
  );
}

getPendingInstructor.PATH = '/api/v1/admin/instructors/pending';
