/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserStatusUpdateRequest } from '../../models/user-status-update-request';

export interface UpdateInstructorStatus$Params {
  instructorId: string;
      body: UserStatusUpdateRequest
}

export function updateInstructorStatus(http: HttpClient, rootUrl: string, params: UpdateInstructorStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, updateInstructorStatus.PATH, 'patch');
  if (params) {
    rb.path('instructorId', params.instructorId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

updateInstructorStatus.PATH = '/api/v1/admin/instructors/{instructorId}/status';
