export * from './adminController.service';
import { AdminControllerService } from './adminController.service';
export * from './authenticationController.service';
import { AuthenticationControllerService } from './authenticationController.service';
export * from './bookingController.service';
import { BookingControllerService } from './bookingController.service';
export * from './classSchedulesController.service';
import { ClassSchedulesControllerService } from './classSchedulesController.service';
export * from './fitnessClassesController.service';
import { FitnessClassesControllerService } from './fitnessClassesController.service';
export const APIS = [AdminControllerService, AuthenticationControllerService, BookingControllerService, ClassSchedulesControllerService, FitnessClassesControllerService];
